---
- hosts: docker
  gather_facts: yes

  tasks:
    - name: Add Docker YUM Repository
      yum_repository:
        name: docker
        description: Docker Repository
        baseurl: https://yum.dockerproject.org/repo/main/centos/7/
        enabled: yes
        gpgcheck: yes
        gpgkey: https://yum.dockerproject.org/gpg

    - name: Install base packages
      package: name={{ item }} state=latest
      with_items:
        - wget
        - screen
        - mlocate
        - vim
        - net-tools
        - telnet
        - docker-engine
        - epel-release

    - name: Start Docker
      service: name=docker state=started enabled=yes
